#Config File for Rocket setup
---
#Files for Motor
githubfiles:
  thrusturl: 'https://raw.githubusercontent.com/RyanSamF/PSP_SL_2024-25/main/CSV_files/Wolf_thrust.csv' #url for thrust
  dragurl: 'https://raw.githubusercontent.com/RyanSamF/PSP_SL_2024-25/main/CSV_files/wolf_cd_openrocket.csv' #url for drag

motor:
  net_mass: 7.8 #mass of motor with propellant in lbs
  prop_mass: 4.01 #mass of propellant in lbs
  center_of_dry_mass: 9.843 #distance from nozzle of center of mass of motor without propellant in in
  dry_inertia: [1.22, 1.22, 0.042] #moment of inertia without propellant in lbs*ft^2 
  #INERTIA NUMBERS NOT UPDATED
  chamber_rad: 1.379 #radius of inside of propellant chamber in in
  chamber_height: 15.748 #height of propellant chamber in inches
  chamber_pos: 8.5 #position of center of propellant chamber inches
  nozzle_rad: 0.625 #radius of nozzle in inches

rocket:
  radius: 2.575 #radius of rocket in in
  mass: 28.5 #mass in lbs
  inertia: [180.28, 180.28, 1.16] #moment of inertia in lbs*ft^2
  COM: 52.749 #center of mass from nose without motor in inches
  length: 95.598 #length of rocket in inches

nose_cone:
  length: 11 #length of nose cone in inches
  
fins:
  n: 3 #number of fins
  root_chord: 5.5 #root chord in inches
  tip_chord: 2 #length of tip chord in inches
  position: 87 #position of top of fins in inches
  span: 6.2 #span of fin in inches
  sweep: 1.82 #sweep length of fins in inches  

parachutes:
  drogue_cd: 0.61  #coefficient of drag of drogue parachute
  main_cd: 2.2 #coefficient of drag of main parachute
  main_trigger: 700 #trigger height for main parachute in ft

...
