#Config File for Rocket setup
---
#Files for Motor
-githubfiles:
  thrusturl: 'https://raw.githubusercontent.com/RyanSamF/PSP_SL_2024-25/main/Wolf_thrust.csv' #url for thrust
  dragurl: #url for drag

-motor:
  net_mass: 4.2 #mass of motor with propellant in lbs
  prop_mass: 1.878 #mass of propellant in lbs
  center_of_dry_mass: 0.248 #distance from nozzle of center of mass of motor without propellant in in
  dry_inertia: [1.22, 1.22, 0.042] #moment of inertia without propellant in lbs*ft^2 
  #INERTIA NUMBERS NOT UPDATED
  chamber_rad: 0.03505 #radius of inside of propellant chamber in in
  chamber_height: 0.4 #height of propellant chamber in ft
  chamber_pos:  
  nozzle_rad: 0.625

-rocket:
  radius: 2.575 #radius of rocket in in
  mass: 15.644 #mass in lbs
  inertia: #moment of inertia in lbs*kg^2
  COM: 52.749 #center of mass from nose without motor in inches
  length: 92.5 #length of rocket in inches

-nose_cone:
  length: #length of nose cone in ft
  kind: #kind of nose cone
  
-fins:
  n: #number of fins
  root_chord: #root chord in ft
  tip_chord: #length of tip chord in ft
  position: #position of
  span: #span of fin in ft
  sweep: #sweep length of fins in ft  

-parachutes:
  drogue_cd: 0.61  #coefficient of drag of drogue parachute
  main_cd: #coefficient of drag of main parachute
  main_trigger: #trigger height for main parachute ft

...
