#Config File for Rocket setup
---
#Files for Motor
-githubfiles:
  thrusturl: 'https://raw.githubusercontent.com/RyanSamF/PSP_SL_2024-25/main/OpenCurve.csv' #url for thrust
  dragurl: #url for drag

-motor:
  net_mass: 4.2 #mass of motor with propellant in lbs
  prop_mass: 1.878 #mass of propellant in lbs
  center_of_dry_mass: 0.248 #distance from nozzle of center of mass of motor without propellant in lbs
  dry_inertia: [0.2499, 0.2499, 0.008603] #moment of inertia without propellant in lbs/ft^2 
  chamber_rad: 0.03505 #radius of inside of propellant chamber in meters
  chamber_height: 0.4 #height of propellant chamber in meters
  chamber_pos:  

-rocket:
  radius: 0.06541 #radius of rocket in meters
  mass: 15.644 #mass in kg
  inertia: #moment of inertia in kg/m^2
  COM: #center of mass from nose without motor in meters

-nose_cone:
  length: #length of nose cone in meters
  kind: #kind of nose cone
  
-fins:
  n: #number of fins
  root_chord: #root chord in meters
  tip_chord: #length of tip chord in meters
  position: #position of
  span: #span of fin in meters
  sweep: #sweep length of fins in meters  

-parachutes:
  drogue_cd: #coefficient of drag of drogue parachute
  main_cd: #coefficient of drag of main parachute
  main_trigger: #trigger height for main parachute 

...